### PR TITLE
Added rebasing of relation after item creation

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by nikosdion** [comment]
An unconditional rebase is the wrong thing to do. In the majority of saves you won't be touching the relation-significant fields so there's no need to rebase. If you do rebase you lose all lazy or eager loaded relation data and you have to go through the database again. This is why I didn't add a rebase() there myself.

**Comment by Skullbock** [comment]
I'm sorry, i'm missing something: if we're doing a new record, the record in the relations is always wrong right?

**Comment by nikosdion** [comment]
You are right, of course. Now that I could see the code on a screen bigger than my cellphone I saw that you put the code in the right place.

**Comment by Skullbock** [comment]
Great! :)

**Pull request merged**
