### PR TITLE
Rework tags

### PR DESCRIPTION
**Pull request by Eighke**
#509 #511

### CODE REVIEW

**Comment by Eighke** [comment]
Uhm not good. getFieldValue doesn't sent value if the database hasn't the named field.

I will need to use another solution, wait before merging it.

**Comment by Eighke** [comment]
@nikosdion Ok now I remember why it was inside the Field and not inside the Model. 

It is not a database field, and we are binding only the database field into the form... I'm checking for an easy solution~'

**Comment by nikosdion** [comment]
OK, I'm not merging anything until you've checked what needs to be done.

**Comment by Eighke** [comment]
Damn `Tags`~

Tag field
* Removed getOptions, we can use the Joomla one
* Added a attribute `front_link` to add the link to the frontend com_tags things (false by default)

Tags behaviour
* Using `getBehaviorParam` with `tagFieldName` to setup the field name (`tags` by default)

DataModel
* I had to readd `getFields()` method for compatibility with `JTableInterface`

So by default we need to use a ```<field name="tags" type="tag" />``` inside the XML form. It is possible to change the field name using ```$this->setBehaviorParam('tagFieldName', 'NewName')``` directly inside the Model.

**Comment by nikosdion** [comment]
So it's not ready?

**Comment by Eighke** [comment]
You can merge it. I tested many action and it looks good.

**Comment by willfaulds** [comment]
@Eighke can you look at com_todo and its implementation of tags (perhaps something is setup wrong but I cannot get tags to persist after save)

Latest FOF3 & com_todo

**Comment by Eighke** [comment]
@willfaulds Sorry didn't see your message. 

I checked and it looks good. But the Tags are quite messy to implement, I always have problem with them. Well everything using UCM is messy anyway.

I'll check on my local version, maybe Joomla updated something and it is broken...

**Comment by willfaulds** [comment]
OK let me know and I'll double check.

**Pull request merged**
