### PR TITLE
Add ordering to form.form.xml created by Scaffolding

### PR DESCRIPTION
**Pull request by Horizak**
Is there any reason to not include ordering field in add task?

if you dont include ordering field, on a new record you get error "COM_STRONGNET_TEST_ERR_ORDERING_EMPTY"

### CODE REVIEW

**Comment by nikosdion** [comment]
Yes, there is. There seems to be a bug with the built-in check() method for NOT NULL fields with a default value. Instead of complaining it should use the default value. Moreover 0 and NULL seem to be causing the same effect as far as validation is concerned. It's on my to-do list.

**Comment by Horizak** [comment]
but if you dont add ordering field in form.form.xml you will never have the option to change the order, even in the edit task.

**Comment by nikosdion** [comment]
The ordering in Joomla! 3 is supposed to be set in the Browse view using drag'n'drop.

**Comment by Horizak** [comment]
ah it's true I forgot this,

I will see built-in check() to find the bug.

**Comment by Horizak** [comment]
Its ok add ordering to fieldsSkipChecks when is new record?

like this;
in Model/DataModel/Behaviour/Created.php  onBeforeCheck function add
$oldPKValue = $model->getId();
if (empty($oldPKValue))
{
	$model->addSkipCheckField('ordering');
}
its correct the problem with ordering in new records, but not for other fields with the same problem.

**Comment by nikosdion** [comment]
Yes, this is a correct temporary solution until I fix `check()` in the DataModel.

**Comment by Horizak** [comment]
you want a PR of this?

i see in check() but i dont see a permanently solution because you have this:
if (($field->Null == 'NO') && empty($value) && !is_numeric($value) && !in_array($fieldName, $this->fieldsSkipChecks))
{
	$text = $this->container->componentName . '_' . $this->container->inflector->singularize($this->getName()) . '_ERR_' . $fieldName . '_EMPTY';
	throw new \RuntimeException(\JText::_(strtoupper($text)), 500);
}

and here the ordering field come with:
$field->Null == 'NO'
empty($value)
and
$field->Default = null

**Comment by nikosdion** [comment]
I want to rethink how the check() method works.

**Comment by nikosdion** [comment]
After today's commits the issue should be resolved. Can you please check and let me know?

**Comment by Horizak** [comment]
ok now for the ordering its ok ;) with commit https://github.com/akeeba/fof/commit/ab773973cce8e6dd5a4915a61f0b57d71857f6e3

In your commit https://github.com/akeeba/fof/commit/969ee76c3dcfc7326654b42407b8dc4966fea7f8
for the ordering field, never enter here because you set value 0 before and now is numeric.

but for other fields maybe this works, as long they have a default value different of null

Sorry about my English :)

**Comment by nikosdion** [comment]
This is intentional :) We were defining the ordering fields in our software as NOT NULL without a default value. I decided to add a special case for the ordering field exactly because of that. I'm lazy :p

**Pull request closed without merging**
