### PR TITLE
Install one or more template with your package like modules and plugins.

### PR DESCRIPTION
**Pull request by Horizak**
This is useful when you need to create one component with modules, plugins and templates to your client

### CODE REVIEW

**Comment by nikosdion** [comment]
I will have to decline this for two reasons.

The first reason is that FOF 2 is going into maintenance mode and all development effort has shifted to FOF 3.

The other reason is that now that Joomla! 2.5 is EOL we are only interested in what's possible with Joomla! 3. In Joomla! 3 you *can* use the package extension type (pkg_something) to install all extensions. All included extension types support installation scripts since Joomla! 3.3. The only reason we had the installation script in FOF was the lack for installation script support in several extension types (modules, packages) under Joomla! 2.5 and 3.0 to 3.2.

In fact, I am reconsidering the inclusion of the installation script in FOF 3. If I keep it, it will be a very cut down version which will only handle extension *uninstallation* on update (removing obsolete modules and plugins) and adding post-installlation messages to the database. The installation of modules, plugins, libraries, templates, whatever with your component will be handled by Joomla! itself.

**Comment by Horizak** [comment]
Then in future components that use fof3 will not have the following installation structure?

com_example.zip
* backend
* fof
* frontend
* language
* media
* strapper
* example.xml
* script.example.php

How you will install your component that need the fof3, strapper, some modules and some plugins?

**Comment by nikosdion** [comment]
I already told you. If you have no idea what a package type extension is: https://docs.joomla.org/Package

**Comment by Horizak** [comment]
Ok I know what is extension type package.
My question is how do we control versions of fof and strapper?

Ok fof is a library and joomla correctly checks the version?

And strapper what will check versions? to not allow replace a recent strapper for an older.

**Comment by nikosdion** [comment]
As of Joomla! 3.3, all types of extensions support installation scripts. Therefore they can CHECK if they are older versions and not install themselves.

**Comment by Horizak** [comment]
excuse my insistence but then it is the strapper?

strapper is not any extension type right? Are media files and for this joomla don`t check versions

**Comment by nikosdion** [comment]
There is the "file" extension type. And yes, it's versioned. And yes, it supports installation scripts. Trust me, I know Joomla! core code inside out.

**Comment by Horizak** [comment]
Thank you

Nice, you will change buildfiles to automatic make new package structure?

**Comment by nikosdion** [comment]
Eventually, yes, I'll add support for these in the Build Files repository. Right now I plan on adding support for getting the latest official FOF and Strapper package for inclusion in the installation package (discovered from the update XML file). This is required to avoid people –including me!– packaging random dev builds of FOF with their extensions. Constructing the package of your extension is still your responsibility.

**Comment by Horizak** [comment]
yes i know..

I use buildfiles to build my extensions now...

When i realese new version, buildfiles prepare my package without fof and strapper and then I insert lastest stable version of fof and strapper from akeeba site.

**Pull request closed without merging**
