### PR TITLE
PHP7 fix

### PR DESCRIPTION
**Pull request by wilsonge**
See https://github.com/joomla/joomla-cms/pull/6434

### CODE REVIEW

**Comment by nikosdion** [comment]
Are you using Rasmus' Vagrant box with PHP 7? Since it's still in flux I'd like to know which distribution you're using.

**Comment by wilsonge** [comment]
I'm not. But I'm just backporting the fix michael made in the framework https://github.com/joomla-framework/utilities/commit/332e60f2eeb09c5775118df2b86759d4ddae5d4d

**Comment by wilsonge** [comment]
It's one of my jobs to set up this week tho

**Comment by nikosdion** [comment]
Good! Let me know how it goes. It's on my ever-growing to-do list. Right now I'm neck deep into refactoring...

**Comment by mbabker** [comment]
The only 3 major things I've seen on the current PHP 7 branch (from Rasmus' Vagrant box and Travis):

- Array to string conversion (fixed here)
- SimpleXMLElement not handling empty nodes the same as in PHP 5
- The current implementation of the [engine exceptions RFC](https://wiki.php.net/rfc/engine_exceptions_for_php7) screws B/C with Exception classes (https://github.com/php/php-src/commit/1c94ff0595bbe6f3df8058aff7252bda09dc4a15#diff-fdeb80468c90d6e27134ef3b9f1b7379R726 is the implementing commit; basically there's a new BaseException object, Exception now extends from it, and EngineException is a separate branch off BaseException)

Otherwise, at least from the Framework repos, things are running smoothly.

**Comment by nikosdion** [comment]
Thanks! The way I see it the SimpleXMLElement could be an issue. The array to string conversion, who knows, I will need to test. The engine exceptions is not causing any b/c issues in my code since the exceptions are bubbled up to Joomla!. I can see why they could be an issue with Joomla!, though. But, hey, new major version, some breakage is to be expected :)

**Comment by wilsonge** [comment]
I'm not sure there is a Simple XML issue. I think there was some issues with more array to string conversions in the registry class. But I haven't seen any other issues there.

**Comment by mbabker** [comment]
Ya, the simple XML thing looks to have been our code and a rather interesting interpretation of the error it was throwing (it was SimpleXML that was tossing a bad error, not the array to string stuff).

As for the exceptions, it's an issue if you have a handler (like the CMS' `set_exception_handler(array('JErrorPage', 'render'));` call in the bootstrap) and your method typehints on Exception as that handler will catch everything thrown in the new branches of the Exception class too.  That one will definitely be fun to code around.

**Pull request merged**
