### PR TITLE
FormField Button : Allow parsing Tags

### PR DESCRIPTION
**Pull request by Cook-Self-Service**
When Button is used in list the onclick event is now parsed and so then can allow allow sending javascript with [ITEM:data]
Example for edit button : onclick="listItemTask('cb[ITEM:ID]', 'edit')"

### CODE REVIEW

**Comment by nikosdion** [comment]
I don't like it. Mixing persistent user input (database data) with client-side scripting is a recipe for disaster. It simply opens up the door to too many security issues.

**Comment by Cook-Self-Service** [comment]
Ok, I understand. You are right. The thing I need is to beeing able to create a simple 'Edit' button in a list. How do I do ? Maybe I missed something ?
What do you think of parsing only the ID field ?

**Comment by nikosdion** [comment]
I had a similar need. So I came up with this method for my J and Beyond 2015 presentation's demo component:

```xml
		<field name="view_sessions" type="Button"
			   class="btn-primary btn-large" icon="icon-info"
			   onclick="window.location=jQuery(this).attr('href')"
			   url="index.php?option=com_jab15&amp;view=Sessions&amp;jab15_conference_id=[ITEM:ID]"
			   text="View sessions"
			   label_placement="empty"/>
```

**Comment by Cook-Self-Service** [comment]
Yes, but this transform a POST request to a GET. I mean I do not need only for edit. I need for any possible task, called in post through the native listItemTask() function.
I can also make a different improvement : accepting a TASK name in the parameter.

**Pull request closed without merging**
