### PR TITLE
Added Service to the container to easily get the component's params from Configuration

### PR DESCRIPTION
**Pull request by Skullbock**
Taken directly from AkeebaSubs 5.0

Example:

```php
$apiKey = $this->container->params->get('api_key', false);
$this->container->params->set('api_key', '1bcde');
$this->container->params->setParams(array('param1' => '123', 'param2' => '345'));
```

### CODE REVIEW

**Comment by nikosdion** [comment]
I love the idea ofnsuch a service but we need to improve it a bit. 

Loading the component parameters should be a public function reload() instead of hard-coded in the constructor. The constructor would call it, but the developer can force reload the parameters if need be. 

Setting and saving the parameters should be two different methods, set() and save().

If you can please do that I will be more than happy to include these features in FOF :)

**Comment by Skullbock** [comment]
Like this?

**Comment by nikosdion** [comment]
Exactly! When you have some time can you document it on the wiki?

**Comment by Skullbock** [comment]
Sure. New page or in the Container page?

**Comment by nikosdion** [comment]
New page, but link to it from the Container documentation

**Comment by Skullbock** [comment]
Done!

**Comment by nikosdion** [comment]
Thank you!

>

**Pull request merged**
