### PR TITLE
Update UCM if needed

### PR DESCRIPTION
**Pull request by Eighke**

### CODE REVIEW

**Comment by Eighke** [comment]
Wait something wrong I think

**Comment by Eighke** [comment]
Ah no I'm just not using the good branch. Looks good. :)

**Comment by nikosdion** [comment]
May I propose an improvement? Instead of having this method being called by the publish and unpublished methods of the DataModel just create an onAfterPublish and onAfterUnpublish method in each behavior and call the model's updateUcmContent method.

Why? Separation of responsibilities. The DataModel MUST NOT know how its attached behaviors work under the hood. With your currently proposed code the DataModel has to know that two specific behaviors use the UCM. It shouldn't.

**Comment by Eighke** [comment]
Oh didn't think about that. Yes looks definitely better.

**Comment by nikosdion** [comment]
Good! Just ping me when you'll have made the changes to the code :)

**Comment by Eighke** [comment]
Good.

**Pull request merged**
