### PR TITLE
Form Field Button - ListItemTask

### PR DESCRIPTION
**Pull request by Cook-Self-Service**
A new introduced attribute in Button Field for sending POST task in the
grid.

### CODE REVIEW

**Comment by nikosdion** [comment]
You need to update your local development branch. All the Pull Requests you are sending are based on a much earlier version of the code meaning that I have to resolve a lot of merge conflicts by hand.

**Comment by Cook-Self-Service** [comment]
I know, but I do not understand how to do it.
I can’t find the option to do it.

Do I need to delete and clone it all again ? I guess not.
I searched over the net and all  get are command lines. At the moment I work with Eclipse and Git application I do not want to do it by command line.

Any help ?

**Comment by tampe125** [comment]
are you under Windows/Mac? Try [SourceTree](https://www.sourcetreeapp.com), it's an amazing GUI for Git

**Comment by Cook-Self-Service** [comment]
Wow, it looks great !
Trying now.

Actually I am already doing command line all day long to reinstall a new server. I do not have patience to git by hand.
Thank a lot.

Is there the option to merge the local repository with the original repository ?

**Comment by tampe125** [comment]
Yes:
http://stackoverflow.com/questions/13273852/how-do-i-update-my-forked-repo-using-sourcetree

FYI the right name for the "original" repo is **upstream**. Using the right name will be useful when you're going to google something

**Pull request merged**
