### PR TITLE
Run tests in php 5.6/7.0/hhvm

### PR DESCRIPTION
**Pull request by photodude**
- Updated Travis Joomla version to the officially supported LTS

### CODE REVIEW

**Comment by nikosdion** [comment]
I'm afraid this could never work due to the way FOF tests work: we had to include the entire Joomla! package inside the environments/x.y subdirectories. Just adding a 3.4 environment won't make Travis somehow download Joomla! 3.4 files.

I don't want to add one more Joomla! version in the FOF repository. Until I find a better way I'm not caring about Travis results and only rely on my local unit test runs.

**Comment by photodude** [comment]
I believe the Joomla Framework is a package available through Composer. I'm not sure if the CMS is available via composer. Something like a composer package seems like it would be the best method for adding the environment for testing on Travis CI without needing including the entire Joomla! package in FOF.

**Comment by nikosdion** [comment]
The Joomla! Framework is of no use to us. FOF runs against Joomla! (the CMS), not Joomla! Framework. Joomla! (the CMS) does use parts of the Joomla! Framework: some of the Joomla! (CMS) library classes extend from JF.

Since Joomla! (the CMS) is not a Composer package we can't use Composer to pull it. I'm thinking that we should probably be using Git to fetch the latest commit of the staging branch OR a specific tag but I hadn't the time to pursue that yet.

**Comment by photodude** [comment]
I have set up a [`.gitmodules` file](http://git-scm.com/docs/gitmodules) for "using Git to fetch the latest commit of the staging branch" which I believe should work. Would you like me to open a new PR for that, or use it from the patch in this PR?
[patterned after the .gitmodules for com_localise](https://github.com/joomla-projects/com_localise/blob/develop/.gitmodules)

**Comment by nikosdion** [comment]
Almost there. We're missing a `Tests/config_travis.php` file. Would you like to add it yourself?

**Comment by nikosdion** [comment]
I also realised that the .gitmodules file isn't committed either.

**Comment by photodude** [comment]
I've added a config_travis.php file to my branch https://github.com/photodude/fof/tree/patch-1

Seems my commits that occurred after the PR was closed don't show up here. I assume if the PR is reopened they would show. I could open a new PR, which should show all the commits.

**Comment by nikosdion** [comment]
Looks like the .travis.yml file has some issues: https://travis-ci.org/akeeba/fof/jobs/61265846

PS: I re-opened the PR. All your commits will now trigger a Travis run. Ping me when you have it working :)

**Comment by photodude** [comment]
@nikosdion I have it working now.

It seems it's mostly about using the command line to add the submodules
`git submodule add -b 3.5-dev https://github.com/joomla/joomla-cms.git Tests/environments/3.5-dev`

References used: 
- http://git-scm.com/book/en/v2/Git-Tools-Submodules
- https://git.wiki.kernel.org/index.php/GitSubmoduleTutorial
- https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

Useful tool for when yaml is unhappy
- http://yaml-online-parser.appspot.com/

**Comment by nikosdion** [comment]
Perfect! Thank you very much for all the work you've put into this – and everything else :)

**Comment by photodude** [comment]
@nikosdion you're welcome, Thank you for considering the contributions.

**Pull request merged**
