### PR TITLE
Color Field / Toolbar improvements

### PR DESCRIPTION
**Pull request by Cook-Self-Service**
This is my fist Pull Request to the project. Only few details let's say. Fixes, small improvements, and little proposal.

### CODE REVIEW

**Comment by nikosdion** [comment]
Can you please make on PR per thing you've changed? This PR has three different items. I can't merge it because I:
1. want to test and document the new field
2. disagree with the changes in AkeebaStrapper
3. can immediately accept the last change (it's a typo)

Unfortunately because of item 2 I can't merge anything at all.

**Comment by Cook-Self-Service** [comment]
I have made only one PR for the first, and then all my commits when automatically in it.
How can I separate them ?

**Comment by Cook-Self-Service** [comment]
What is the problem for .2 ? Is is incorrectly coded ? Because this is a real working fix. Then It might exist another way for fixing it, right ?
I can send you a screenshot, it is really a problem to have the grid on 10 columns instead of 12 when the sidebar margin is not displayed in front.
How can I remove this commit from the Pull Request ? Sorry, I am still learning to Git....

**Comment by Cook-Self-Service** [comment]
I don't know how to split or remove this commits. I tried to rollback, to revert commit. But the changes only happens in my local files. Impossible to change anything here. Do I need to create a new branch for every pull request ?

**Comment by nikosdion** [comment]
You need to create one branch per change so that you can submit one PR per change (PRs in GitHub are linked to branches).

**Comment by Cook-Self-Service** [comment]
Done.
I removed the changes in Akeeba Straper manualy editing the file (Here in github.com editor.)

**Comment by nikosdion** [comment]
Are there any attributes I should be aware of for the Color field? I want to write the documentation :)

**Comment by Cook-Self-Service** [comment]
Thanks.
There is no attributes for the Color Field.
The div style is hardcoded a simple 20x20px square with the given color in the lists.
The form is reusing the native Joomla color field.
In the value, the prefix hash symbol can be present or absent it doesn't matter.
It works only for hexadecimal colors. (not using color names)
For further Pull request I will always create a branch for every different feature proposed or fixed.
Thank you for beeing patient with me, I am learning in the same time.

**Pull request merged**
